name: GitHub CI
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:
    inputs:

env:
  MAIN_PYTHON_VERSION: '3.9'
  CONTAINER_TAG: 'latest'
  PACKAGE_NAME: 'ansys-dpf-composites'
  DOCUMENTATION_CNAME: 'composites.dpf.docs.pyansys.com'
  PYDPF_COMPOSITES_DOCKER_CONTAINER_PORT: "50052"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
          python -m pip install --upgrade poetry

      - name: Test with tox
        run: tox -e style

  doc-style:
    name: "Documentation style"
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/doc-style@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: "Tests and coverage"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We can't test on windows because it is not possible to run linux
        # docker images on the windows agents. See the issue
        # https://github.com/actions/runner-images/issues/1143
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    steps:
      - name: "Login in Github Container registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pull and start dpf container"
        run:  |
          docker pull ghcr.io/ansys/pydpf-composites:${{ env.CONTAINER_TAG }}

      - name: "Checkout the project"
        uses: actions/checkout@v3

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          python -m pip install --upgrade poetry

      - name: "Test with tox"
        # Only the tox environment specified in the tox.ini gh-actions is run
        run: |
          tox
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

      # enable for debugging purposes. Ensure that the output does not contain
      # pipeline secrets.
      # - name: "Upload server output"
      #  if: always()
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: server_output
      #    path: tests/logs/*_log_*.txt
      #    retention-days: 7

  tests_minimal_version:
    name: "Test with lower-bound dependency versions"
    runs-on: ubuntu-latest

    steps:
      - name: "Login in Github Container registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Pull and start DPF container"
        run: |
          docker pull ghcr.io/ansys/pydpf-composites:${{ env.CONTAINER_TAG }}
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          python -m pip install --upgrade poetry

      - name: Test with tox
        run: |
          tox -e test-minimal
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

  doc-build:
    name: "Documentation build"
    runs-on: ubuntu-latest
    steps:
      - name: "Install OS packages"
        run: |
          sudo apt update
          sudo apt-get install pandoc xvfb

      - name: "Login in Github Container registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pull and start dpf container"
        run: |
          docker pull ghcr.io/ansys/pydpf-composites:${{ env.CONTAINER_TAG }}
          docker run -d --restart always -p 50052:50052 -e ANSYSLMD_LICENSE_FILE=1055@${{ secrets.LICENSE_SERVER }} -e ANSYS_DPF_ACCEPT_LA=Y ghcr.io/ansys/pydpf-composites:${{ env.CONTAINER_TAG }}

      - name: "Checkout the project"
        uses: actions/checkout@v3

      - name: "Set up Python ${{ env.MAIN_PYTHON_VERSION }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip tox
          python -m pip install --upgrade poetry

      - name: "Generate the documentation with tox"
        run: |
          tox -e doc-linux

      - name: "Upload HTML Documentation"
        uses: actions/upload-artifact@v3
        with:
          name: documentation-html
          path: .tox/doc_out/html
          retention-days: 7

      - name: "Install OS packages for PDF"
        run: |
          sudo apt-get install latexmk texlive-latex-extra

      - name: "Generate the PDF documentation with tox"
        run: |
          tox -e doc-linux-pdf

      - name: "Upload PDF Documentation"
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: .tox/doc_out/latex/ansys-dpf-composites.pdf
          retention-days: 7

  build-library:
    name: "Build package"
    runs-on: ubuntu-latest
    needs: [doc-style, doc-build, code-style, tests, tests_minimal_version]
    steps:
      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}

  build-wheelhouse:
    name: "Build wheelhouse for latest Python versions"
    runs-on: ${{ matrix.os }}
    needs: [doc-style, doc-build, code-style, tests, tests_minimal_version]
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest]
          python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: "Build a wheelhouse of the Python library"
        uses: ansys/actions/build-wheelhouse@v4
        with:
          library-name: "ansys-dpf-composites"
          library-namespace: "ansys.dpf.composites"
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-library, build-wheelhouse]
    steps:
      - uses: ansys/actions/doc-deploy-dev@v4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          force-orphan: false

  release:
    name: "Release project"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    needs: [build-library, build-wheelhouse]
    runs-on: ubuntu-latest
    steps:

      - name: "Release to the public PyPI repository"
        uses: ansys/actions/release-pypi-public@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYPI_TOKEN }}

      - name: "Release to GitHub"
        uses: ansys/actions/release-github@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    steps:
      - uses: ansys/actions/doc-deploy-stable@v4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          force-orphan: false
