name: GitHub CI
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:
    inputs:

env:
  MAIN_PYTHON_VERSION: '3.13'
  CONTAINER_TAG: 'latest'
  PACKAGE_NAME: 'ansys-dpf-composites'
  DOCUMENTATION_CNAME: 'composites.dpf.docs.pyansys.com'
  PYDPF_COMPOSITES_DOCKER_CONTAINER_PORT: "50052"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-wheelhouse:
    name: "Build wheelhouse for latest Python versions"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest]
          python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: "Build a wheelhouse of the Python library"
        uses: ansys/actions/build-wheelhouse@fix/build-wheelhouse-poetry
        with:
          library-name: "ansys-dpf-composites"
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

