name: Package cleanup
on:
  workflow_dispatch:
  schedule: # UTC at 0200
    - cron: "0 2 * * *"

permissions:
  contents: write
  packages: write

jobs:
  cleanup:
    name: "Delete untagged package versions"
    runs-on: ubuntu-latest
    steps:
      - name: "Delete untagged package versions"
        uses: ansys/actions/hk-package-clean-untagged@v5
        with:
          package-name: 'pydpf-composites'
          allow-last-days: '14'
          token: ${{ secrets.GITHUB_TOKEN }}
